[package]
name = "colornamer"
version = "0.1.0"
authors = ["Tony Crisci <tony@dubstepdish.com>"]

[dependencies]
lazy_static = "1.0"
bitflags = "1.0"

[dev-dependencies]
criterion = "0.1.2"

[[bench]]
name = "basic"
harness = false
